export const portfolioConfig = {
  personal: {
    name: "Van Lumban",
    title: "Senior Mobile Developer",
    tagline: "7+ years building production apps. Banking, gaming, travel, e-commerce. If it is mobile, I build it.",
    location: "Philippines | Open to Remote Work",
    status: "Available 24/7",
    contactCta: {
      heading: "Have an app idea?",
      subheading: "Let's build something amazing.",
      buttonText: "Get in Touch",
    },
  },

  social: {
    github: "https://github.com/vanlumban",
    linkedin: "https://www.linkedin.com/in/lumban-vjm/",
    email: "lumban.vjm@gmail.com",
    phone: "+639266870932",
  },

  services: [
    {
      num: "01",
      title: "Native Android Development",
      description: "Building performant, production-ready Android apps that users love. From concept to Play Store.",
      stack: ["Kotlin", "Jetpack Compose", "MVVM", "Java"],
    },
    {
      num: "02",
      title: "Flutter Development",
      description: "Cross-platform apps with native feel. One codebase for both Android and iOS.",
      stack: ["Dart", "Flutter", "Provider", "Riverpod"],
    },
    {
      num: "03",
      title: "Website Development",
      description: "Responsive, fast, modern web applications. Landing pages to full web apps.",
      stack: ["React", "Next.js", "TypeScript"],
    },
  ],

  stack: {
    Languages: ["Kotlin", "Java", "Dart", "TypeScript"],
    Libraries: ["Retrofit", "Volley", "Okhttp", "Dagger", "Firebase", "Coil", "AppsFlyer"],
    Tools: ["Android Studio", "Gradle", "Git", "Figma", "Postman"],
    Databases: ["Firebase Realtime DB", "Room"],
    Testing: ["Espresso", "JUnit", "Mockito"],
    Deployment: ["Fastlane", "Firebase", "Bitrise", "AppCenter", "Google Play"],
  },

  companies: [
    { name: "Cognizant", logo: "images/cognizant.png" },
    { name: "Whitecloak Technologies", logo: "images/whitecloak.png" },
    { name: "Corex Studio", logo: "images/corex-studio.jpg" },
    { name: "Bigcat Software Solutions", logo: "images/bigcat.jpg" },
    { name: "Takefive Outdoors", logo: "images/takefive-outdoors.png" },
  ],

  apps: [
    {
      id: 1,
      title: "Airlines",
      fullTitle: "Airlines Booking",
      icon: "A",
      color: "#3b82f6",
      industry: "Travel",
      description: "Book flights, check in, and manage your boarding pass from your phone. Get real-time flight updates and never miss a beat.",
      technologies: ["Java", "Kotlin", "Jetpack Compose", "MVVM", "MVI"],
      link: "https://play.google.com/store/apps/details?id=com.alaskaairlines.android&hl=en",
      downloads: "5M+",
      rating: 4.7,
      image: "images/airlines_app_banner.png",
      splashImage: "images/loading_alaska_airlines.jpeg",
      lastUpdated: "June 2025",
    },
    {
      id: 2,
      title: "Gaming",
      fullTitle: "Gaming Hub",
      icon: "G",
      color: "#8b5cf6",
      industry: "Gaming",
      description: "Live sports betting, casino games, slots, and virtual sports all in one app. Supports multiple languages and fast transactions.",
      technologies: ["Kotlin", "Jetpack Compose", "WebView", "MVVM"],
      link: "https://www.m88.com/mobile",
      downloads: "1M+",
      rating: 4.5,
      image: "images/casino_app_banner.png",
      splashImage: "images/loading_m88.jpeg",
      lastUpdated: "June 2025",
    },
    {
      id: 3,
      title: "Banking",
      fullTitle: "Mobile Banking",
      icon: "B",
      color: "#10b981",
      industry: "Fintech",
      description: "Handle your banking on the go. Send money, pay bills, check balance, manage cards, and split expenses.",
      technologies: ["Java", "Kotlin", "MVVM", "Retrofit"],
      link: "https://play.google.com/store/apps/details?id=com.unionbankph.online&hl=en",
      downloads: "10M+",
      rating: 4.7,
      image: "images/banking_app_banner.png",
      splashImage: null,
      lastUpdated: "June 2025",
    },
    {
      id: 4,
      title: "Outdoor",
      fullTitle: "Outdoor Adventures",
      icon: "O",
      color: "#f59e0b",
      industry: "Travel",
      description: "Find and book trips to mountains, beaches, and waterfalls. Check schedules and reserve your adventure spot.",
      technologies: ["Kotlin", "MVVM", "Firebase"],
      link: "https://play.google.com/store/apps/details?id=com.darkcloak.android.takefive&hl=en",
      downloads: "10K+",
      rating: 4.6,
      image: "images/travel_app_banner.png",
      splashImage: null,
      lastUpdated: "June 2025",
    },
    {
      id: 5,
      title: "Mall",
      fullTitle: "Retail Mall",
      icon: "M",
      color: "#ec4899",
      industry: "Retail",
      description: "Your shopping buddy at the mall. Free WiFi, movie tickets, rewards points, and store info all in one place.",
      technologies: ["Kotlin", "MVVM", "Firebase", "MappedIn"],
      link: "https://play.google.com/store/apps/details?id=com.ayalamalls.zing&hl=en&pli=1",
      downloads: "1M++",
      rating: 3.2,
      image: "images/mall_app_banner.png",
      splashImage: null,
      lastUpdated: "June 2025",
    },
  ],

  contact: {
    formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSfJvl_aYKLqVVZngIDV31HfUyZYxFpLRVUvIJ9hL2vGUmbCMQ/formResponse",
    fieldIds: {
      name: "entry.168054364",
      email: "entry.1096951385",
      company: "entry.1853628948",
      phone: "entry.514276364",
      projectType: "entry.2018294421",
      budget: "entry.1596272576",
      timeline: "entry.197388172",
      message: "entry.1945337757",
    },
  },
}

export type PortfolioConfig = typeof portfolioConfig